### PR TITLE
Add Event.custom

### PR DESCRIPTION
**Pull request by rtfeldman**
See https://github.com/eeue56/elm-html-test/pull/29/files/8369f064287ca2692b60f79da9ae1279688c1274#diff-bb04a6441906f123b8fabc331ba4634e

### CODE REVIEW

**Comment by rtfeldman** [comment]
@eeue56 ping! 😄

**Comment by rtfeldman** [comment]
@eeue56 I'd like to do a release - are we good without this, or do you think it's necessary? Or something else?

**Comment by eeue56** [comment]
sorry, been busy

**Comment by rtfeldman** [comment]
It's all good, thanks! 🤘

**Pull request merged**
