### PR TITLE
make Event.expect more flexible to support more use cases

### PR DESCRIPTION
**Pull request by gyzerok**
Fixes: https://github.com/eeue56/elm-html-test/issues/61

I figured out it might be easier to discuss with the code ready. So you can see how tests, docs and error messages might look like.

### CODE REVIEW

**Comment by gyzerok** [comment]
@eeue56 have you had a chance to look into proposed changes?

**Comment by harrysarson** [comment]
Hi @gyzerok 

Would this change mean that people would get less informative error messages when checking equality of messages?

**Comment by gyzerok** [comment]
Hello @harrysarson!

Not sure I follow the question. Is something unclear for you in PR changes? Do you have any proposals about how failure reports should be changed there?

**Comment by gyzerok** [comment]
It seems like it won't happen anyway, since the package got merged with `elm-test`

**Pull request closed without merging**
