### PR TITLE
Fix children

### LINKED ISSUE #39: I'm confused over how to use Query.children
The docs say:
> Return the matched element's immediate child elements.
> http://package.elm-lang.org/packages/eeue56/elm-html-test/5.1.0/Test-Html-Query#children

This isn't quite the behavior I'm seeing. When passed a selector, it seems to return the children **and** the parent. 
```
test "The <ul> has 3 children" <|
                \() ->
                    div []
                        [ ul []
                            [ li [] [ text "first item" ]
                            , li [] [ text "second item" ]
                            , li [] [ text "third item" ]
                            ]
                        ]
                        |> Query.fromHtml
                        |> Query.find [ Selector.tag "ul" ]
                        |> Query.children [ Selector.class "" ]
                        |> Query.count (Expect.equal 3)
```

```
✗ The <ul> has 3 children

    ▼ Query.fromHtml

        <div>
            <ul>
                <li>
                    first item
                </li>
                <li>
                    second item
                </li>
                <li>
                    third item
                </li>
            </ul>
        </div>


    ▼ Query.find [ tag "ul" ]

        1)  <ul>
                <li>
                    first item
                </li>
                <li>
                    second item
                </li>
                <li>
                    third item
                </li>
            </ul>


    ▼ Query.children [ class "" ]

        1)  <ul>
                <li>
                    first item
                </li>
                <li>
                    second item
                </li>
                <li>
                    third item
                </li>
            </ul>

        2)  <li>
                first item
            </li>

        3)  <li>
                second item
            </li>

        4)  <li>
                third item
            </li>


    ▼ Query.count

    4
    ╷
    │ Expect.equal
    ╵
    3
```

--------
When not passed any selectors, it seems to only return the parent.
```
test "The <ul> has 3 children" <|
                \() ->
                    div []
                        [ ul []
                            [ li [] [ text "first item" ]
                            , li [] [ text "second item" ]
                            , li [] [ text "third item" ]
                            ]
                        ]
                        |> Query.fromHtml
                        |> Query.find [ Selector.tag "ul" ]
                        |> Query.children []
                        |> Query.count (Expect.equal 3)
```
```
✗ The <ul> has 3 children

    ▼ Query.fromHtml

        <div>
            <ul>
                <li>
                    first item
                </li>
                <li>
                    second item
                </li>
                <li>
                    third item
                </li>
            </ul>
        </div>


    ▼ Query.find [ tag "ul" ]

        1)  <ul>
                <li>
                    first item
                </li>
                <li>
                    second item
                </li>
                <li>
                    third item
                </li>
            </ul>


    ▼ Query.children []

        1)  <ul>
                <li>
                    first item
                </li>
                <li>
                    second item
                </li>
                <li>
                    third item
                </li>
            </ul>


    ▼ Query.count

    1
    ╷
    │ Expect.equal
    ╵
    3
```

Is this the expected behavior?

### PR DESCRIPTION
**Pull request by stoeffel**
this fixes #39 

paired with @samgerber

### CODE REVIEW

**Comment by eeue56** [comment]
lgtm! thanks both!

**Comment by stoeffel** [comment]
@eeue56 elm-package is obviously suggesting a patch release, but this is actually a breaking change. It completely changes the behaviour of `children`. What do you think? bumping to `6.0.0`? Do you have other major changes, that should be bundled with a major bump? or do you think it's fine to release this as 5.1.1?

**Comment by eeue56** [comment]
IMO this is a patch release because although it is a breaking change for someone, the old logic was wrong, and this patch fixes that :)

**Comment by stoeffel** [comment]
okay. I'm fine with that.

**Comment by stoeffel** [comment]
published with v5.1.1 (cc @samgerber)

**Pull request merged**
